repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.6.0"
    hooks:
    - id: check-ast
      # Check whether files parse as valid Python.
    - id: check-merge-conflict
      # Check for files that contain merge conflict strings.
    - id: check-toml
      # Check TOML file syntax.
    - id: check-yaml
      # Check YAML file syntax.

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.4.1"
    hooks:
      - id: ruff
        types: [file, python]
        args: [--fix, --show-fixes]
      - id: ruff-format
        types: [file, python]

  - repo: https://github.com/codespell-project/codespell
    rev: "v2.2.6"
    hooks:
    - id: codespell
      types_or: [python, markdown]
      additional_dependencies: [tomli]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.9.0'
    hooks:
    - id: mypy
